### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gfigueroaalmera** [zirkelc/aws-sigv4-fetch#1]
Alwats response 403 I am using credential us adminAccess

**Comment by zirkelc** [comment]
Could you post please your code how you use it (omitting the credentials) and the error message you receive along the HTTP status?

**Comment by zirkelc** [comment]
@gfigueroaalmera I think I identified the issue. The HTTP method must be in uppercase, otherwise the signature will not be calculated correctly. I added a testcase for IAM get current user. You can run it locally with `npm test` to verify if it works now.
