### ISSUE TITLE
encodeURI does not escape wildcard character '*'

### ISSUE THREAD

**Issue by l20DfX35JnKBfRn** [zirkelc/aws-sigv4-fetch#10]
Hi, I've had an issue using this package, I tried to fetch a path with wildcard character inside of it, e.g. 'GET /documents_*'

According to [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#description) in the MDN docs, it says 

`It escapes all characters except:
A–Z a–z 0–9 - _ . ! ~ * ' ( )`

To fix this I had to manually escape the path to `GET /documents_%2A` and it worked

**Comment by zirkelc** [comment]
Hi @l20DfX35JnKBfRn 

special characters have to be encoded manually via either `encodeURI` or `encodeURIComponent`. Unfortunately, this is not something that I can add because the library only receives an URL without knowing if it is already encoded or not. If I were to apply `encodeURI` by default, I might run into issues like this:

![image](https://github.com/zirkelc/aws-sigv4-fetch/assets/950244/cca7cb4e-28d4-444d-afa9-8e4f9158c076)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

I'm not 100% sure, but I assume you would get the same issues if you were using `fetch()` directly. Is there a way you could verify this?

**Comment by l20DfX35JnKBfRn** [comment]
I'm not sure if I explained myself correctly either

it's more like there's a mismatch between what AWS expected vs what this package generated, I think the AWS sig expects * => %2A and hence why it failed

let me try reproduce it later 👍

**Comment by zirkelc** [comment]
Ah, I see! Are you getting a signature mismatch exception/error?

That would be great if you could reproduce it somehow.

Thank you for the positive feedback! :-)

**Comment by ricksterhd123** [comment]
Hi it's me again

I found this https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html#:~:text=URI%20encode%20every%20byte%20except%20the%20unreserved%20characters%3A%20%27A%27%2D%27Z%27%2C%20%27a%27%2D%27z%27%2C%20%270%27%2D%279%27%2C%20%27%2D%27%2C%20%27.%27%2C%20%27_%27%2C%20and%20%27~%27.

It refers to their java library https://github.com/aws/aws-sdk-java/blob/620bf345b9d57d2be6882bc48d5dddbf9851ebd8/aws-java-sdk-core/src/main/java/com/amazonaws/util/SdkHttpUtils.java#L82

It replaces "*" to "%2A"

What I find quite strange, is that this library uses the official signer from aws-sdk no?

```js
encodeURIComponent(`!*'()`) // => "!*'()"
```

I've not had any other issues except with '*'

Seems like others have had the same issue
https://github.com/aws/aws-sdk-js-v3/issues/2596

Noticed that `@aws-sdk/signature-v4` could do with an update

I can't seem to reproduce it with postman / webhook.site, Postman uses a different method and seems to escape * correctly, if I try to reproduce the same request, postman will sign some headers while fetch does not.

I think testing with a simple IAM_AUTH enabled API Gateway might work.

It's not a massive issue for me, for now, I just do .replaceAll("*", "%2A"), it may be worth a note to the developer in case this fix might break compatibility.

**Comment by zirkelc** [comment]
Hi @ricksterhd123 

thanks for the investigation! Your first link (https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html) handles the case when the AWS SignatureV4 is added to the URL via a query string. However, this library adds the SignatureV4 as HTTP `Authorization` header. So there may be some differences between the two options.

The official package `@aws-sdk/signature-v4` has been moved to `@smithy/signature-v4` in the latest releases. I have planned to switch all dependencies to `@smithy/*` (see #8).

I'm going to prepare a PR that adopts the new dependencies and then I will release it as an alpha package, so you could check if that already fixes this issues.

Also I would like to add a few more E2E tests that interact with the AWS API directly. Currently, there is only one test for IAM (https://github.com/zirkelc/aws-sigv4-fetch/blob/main/test/iam/index.test.ts) because that is quite easy to do on CI. Before I do that, could you please explain in some detail what kind of requests you do to AWS that requires the `*` character in the URL? Is it it an API Gateway route that contains the `*` as part of the path?  Do you also have problems with other AWS services?

Thank you both for your support on this! 👍

**Comment by ricksterhd123** [comment]
> what kind of requests you do to AWS that requires the * character in the URL?

Hi using elasticsearch on AWS, specifically _msearch endpoint

> I'm going to prepare a PR that adopts the new dependencies and then I will release it as an alpha package, so you could check if that already fixes this issues.

Awesome, ping me and I'll have a go

**Comment by zirkelc** [comment]
Hi @ricksterhd123 

I published an alpha version with the new packages from `@smithy/*` (#8), you should be able to install it:

```
npm i aws-sigv4-fetch@alpha
```

Let me know if this issue still persists.

I was also able to setup an e2e for API Gateway, I will continue to investigate if I can reproduce this issue somehow.

**Comment by l20DfX35JnKBfRn** [comment]
Many thanks will get back this evening :)

**Comment by ricksterhd123** [comment]
Hi, sorry I'm late

## package.json
```json
  "dependencies": {
    "aws-sigv4-fetch": "^3.0.0"
  }
```

## WORKING:

```javascript
const { createSignedFetcher } = require('aws-sigv4-fetch');

const signedFetch = createSignedFetcher({ service: 'es', region: 'eu-west-2' });
const OS_DOMAIN = 'https://#####################.eu-west-2.es.amazonaws.com';
const url = `${OS_DOMAIN}/test-%2A`;


(async () => {
    const response = await signedFetch(url, {
        method: 'get',
        headers: { 'Content-Type': 'application/json' }
    });

    console.log(response.status);

    console.log(await response.text());
})();
```
```
200
{}
```

## NOT WORKING:

```javascript
const { createSignedFetcher } = require('aws-sigv4-fetch');

const signedFetch = createSignedFetcher({ service: 'es', region: 'eu-west-2' });
const OS_DOMAIN = 'https://#####################.eu-west-2.es.amazonaws.com';
const url = `${OS_DOMAIN}/test-*`;


(async () => {
    const response = await signedFetch(url, {
        method: 'get',
        headers: { 'Content-Type': 'application/json' }
    });

    console.log(response.status);

    console.log(await response.text());
})();

```

```
403
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/test-%2A\n\ncontent-type:application/json\nhost:#####################.eu-west-2.es.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c###afbf4c8996fb92427ae41e4649b934ca4###91b7852b###\nx-amz-date:20240327T043321Z\n\ncontent-type;host;x-amz-content-sha256;x-amz-date\ne3b0c44298###c149afbf4c8996fb92427ae41e4649b###ca495991b7852b###'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20240327T043321Z\n20240###/eu-west-2/es/aws4_request\n199277059b90bf9723bc3a44b5dca99c30632865e0f7d2a5310b93caee4ce###'\n"}
```

**Comment by ricksterhd123** [comment]
Now trying the new version, `-alpha`

```
  "dependencies": {
    "aws-sigv4-fetch": "^3.0.1-alpha.0"
  }
```

Using the non-working example above:
```
const { createSignedFetcher } = require('aws-sigv4-fetch');

const signedFetch = createSignedFetcher({ service: 'es', region: 'eu-west-2' });
const OS_DOMAIN = 'https://#####################.eu-west-2.es.amazonaws.com';
const url = `${OS_DOMAIN}/test-*`;


(async () => {
    const response = await signedFetch(url, {
        method: 'get',
        headers: { 'Content-Type': 'application/json' }
    });

    console.log(response.status);

    console.log(await response.text());
})();
```

```
403
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/test-%2A\n\ncontent-type:application/json\nhost ...
```

The workaround version still works :)

I'm not sure if this is just a strange quirk with opensearch given that it's a managed service, it might not be handling IAM requests in the same manner as other AWS-owned services.

I think a simple warning may suffice - can you sanity check this for me? All I did was simple AWS Console public opensearch cluster, using fine-grained access with IAM access policy so i setup SAML/use iam auth for API

**Comment by zirkelc** [comment]
Hi @ricksterhd123 

thanks for the investigation. I did some tests on my own with API gateway (see `/test/api-gateway`) and could confirm that the `*` and other characters must be escaped according to [RFC 3986](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent?retiredLocale=de#encoding_for_rfc3986). It's a bit difficult to find official info from AWS, there is this part on the AWS SignatureV4 docs:

https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html
> URI encode every byte. UriEncode() must enforce the following rules:
> - URI encode every byte except the unreserved characters: 'A'-'Z', 'a'-'z', '0'-'9', '-', '.', '_', and '~'.
> - The space character is a reserved character and must be encoded as "%20" (and not as "+").
> - Each URI encoded byte is formed by a '%' and the two-digit hexadecimal value of the byte.
> - Letters in the hexadecimal value must be uppercase, for example "%1A".
> - Encode the forward slash character, '/', everywhere except in the object key name. For example, if the object key name is photos/Jan/sample.jpg, the forward slash in the key name is not encoded.
>
> **Important**
> The standard UriEncode functions provided by your development platform may not work because of differences in implementation and related ambiguity in the underlying RFCs. We recommend that you write your own custom UriEncode function to ensure that your encoding will work.
> To see an example of a UriEncode function in Java, see [Java Utilities](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/SdkHttpUtils.java#L66) on the GitHub website.

I implemented the RFC 3986 encoding in PR #13 and it can be toggled via the `options.encodeRfc3986` boolean flag. I'm not sture yet if it should be enabled by default. I need to check how this encoding affects the Lambda integration (API Gateway Lambda integration or directly via Lambda Function URL). For example, if I request the path `/foo-*` will Lambda receive the original path `foo-*` or the encoded `foo-%2A`?

I released the PR as new version `3.0.1-alpha.1`. 
@ricksterhd123 @l20DfX35JnKBfRn could you install the new alpha version and verify if the request to OpenSearch works if `options.encodeRfc3986: true`?

**Comment by ricksterhd123** [comment]
Hi, I agree fully, perhaps there's a way to enable it by default with backwards compatibility

You'd have to take the same approach the java library does in link above

I hope this issue finds someone who has the same problem I had and helps them to resolve it quickly :)

**Comment by ricksterhd123** [comment]
I'll get back to you on that last request cheers

**Comment by zirkelc** [comment]
I investigated it a bit further and I think this is a bug of the official AWS SignatureV4 implementation. I described it this issue: https://github.com/smithy-lang/smithy-typescript/issues/1224

**Comment by ricksterhd123** [comment]
> I investigated it a bit further and I think this is a bug of the official AWS SignatureV4 implementation. I described it this issue: [smithy-lang/smithy-typescript#1224](https://github.com/smithy-lang/smithy-typescript/issues/1224)

Nice one

I just tested this more, and it seems with `encodeRfx3986` enabled, both `/test-*` and `test-%2A` work the same

**Comment by zirkelc** [comment]
Thanks for verifying this!

I'll wait a few more days, hoping to get confirmation on https://github.com/smithy-lang/smithy-typescript/issues/1224, and then I'll go ahead and encode the URIs by default.

**Comment by zirkelc** [comment]
Hi @l20DfX35JnKBfRn and @ricksterhd123 

my PR (https://github.com/smithy-lang/smithy-typescript/pull/1226) got merged yesterday and I just released a new version of this package. My e2e tests with API gateway are green now, so I hope your issues with OpenSearch should also be resolved.

Please make sure to install the latest version 3.1.0 of this package.
