### ISSUE TITLE
Is `@aws-sdk/client-cognito-identity-provider` used?

### ISSUE THREAD

**Issue by patrickberkeley** [zirkelc/aws-sigv4-fetch#15]
`@aws-sdk/client-cognito-identity-provider` is [listed in this project's `dependencies`](https://github.com/zirkelc/aws-sigv4-fetch/blob/b4630d7843b406ec3d140ba7d151bb22322d1c52/package.json#L46). Is it used/necessary as part of this project?

**Comment by zirkelc** [comment]
Hi @patrickberkeley 

no, it's not used! I created #16 that removes this dependency. Thanks for pointing it out! 👍
