### ISSUE TITLE
Issue with Ignoring AbortSignal and 'init' Fields in fetch Request

### ISSUE THREAD

**Issue by omercz71** [zirkelc/aws-sigv4-fetch#6]
When attempting to add an AbortSignal to the fetch parameters, I encountered an issue where the code appears to disregard the provided AbortSignal. Additionally, it seems that all init fields, except for header, body, and method, are being ignored.

https://github.com/zirkelc/aws-sigv4-fetch/blob/main/src/create-signed-fetcher.ts#L59

**Expected Behavior:**
I expected the provided AbortSignal to function correctly, and all fields within the init object to be respected by the fetch request.

**Comment by omercz71** [comment]
The fix works (at least the signal issue I had)

**Comment by zirkelc** [comment]
Great! I'm about to go on vacation for a few weeks and won't be able to add a proper test before. Therefore, I will leave this fix in the `next` package until I'm back. I'll ping you on this thread when it's released.
